import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Game Generator - Interactive Games',
  description: 'Play interactive games generated by AI prompts',
  other: {
    'fc:frame': 'vNext',
    'fc:frame:image': `${process.env.NEXT_PUBLIC_URL || 'http://localhost:3000'}/api/frame-image`,
    'fc:frame:button:1': 'Play Games',
    'fc:frame:post_url': `${process.env.NEXT_PUBLIC_URL || 'http://localhost:3000'}/api/frame`,
  },
};

export default function FrameLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}